// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
	"database/sql"
)

const createCatalogEntry = `-- name: CreateCatalogEntry :one
INSERT INTO catalog_entries (user_id, game_id, status)
VALUES (?, ?, ?)
RETURNING id, user_id, game_id, status, created_at, updated_at
`

type CreateCatalogEntryParams struct {
	UserID int64
	GameID int64
	Status string
}

func (q *Queries) CreateCatalogEntry(ctx context.Context, arg CreateCatalogEntryParams) (CatalogEntry, error) {
	row := q.db.QueryRowContext(ctx, createCatalogEntry, arg.UserID, arg.GameID, arg.Status)
	var i CatalogEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCatalogEntry = `-- name: DeleteCatalogEntry :exec
DELETE FROM catalog_entries WHERE id = ? AND user_id = ?
`

type DeleteCatalogEntryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteCatalogEntry(ctx context.Context, arg DeleteCatalogEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCatalogEntry, arg.ID, arg.UserID)
	return err
}

const getCatalogEntry = `-- name: GetCatalogEntry :one
SELECT ce.id, ce.user_id, ce.game_id, ce.status, ce.created_at, ce.updated_at,
       g.title, g.cover_url, g.description, g.release_date
FROM catalog_entries ce
JOIN games g ON ce.game_id = g.id
WHERE ce.id = ? AND ce.user_id = ?
`

type GetCatalogEntryParams struct {
	ID     int64
	UserID int64
}

type GetCatalogEntryRow struct {
	ID          int64
	UserID      int64
	GameID      int64
	Status      string
	CreatedAt   string
	UpdatedAt   string
	Title       string
	CoverUrl    sql.NullString
	Description sql.NullString
	ReleaseDate sql.NullString
}

func (q *Queries) GetCatalogEntry(ctx context.Context, arg GetCatalogEntryParams) (GetCatalogEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getCatalogEntry, arg.ID, arg.UserID)
	var i GetCatalogEntryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.CoverUrl,
		&i.Description,
		&i.ReleaseDate,
	)
	return i, err
}

const getCatalogEntryByUserAndGame = `-- name: GetCatalogEntryByUserAndGame :one
SELECT id FROM catalog_entries
WHERE user_id = ? AND game_id = ?
`

type GetCatalogEntryByUserAndGameParams struct {
	UserID int64
	GameID int64
}

func (q *Queries) GetCatalogEntryByUserAndGame(ctx context.Context, arg GetCatalogEntryByUserAndGameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCatalogEntryByUserAndGame, arg.UserID, arg.GameID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCatalogEntries = `-- name: ListCatalogEntries :many
SELECT ce.id, ce.user_id, ce.game_id, ce.status, ce.created_at, ce.updated_at,
       g.title, g.cover_url, g.description, g.release_date
FROM catalog_entries ce
JOIN games g ON ce.game_id = g.id
WHERE ce.user_id = ?
ORDER BY ce.updated_at DESC
`

type ListCatalogEntriesRow struct {
	ID          int64
	UserID      int64
	GameID      int64
	Status      string
	CreatedAt   string
	UpdatedAt   string
	Title       string
	CoverUrl    sql.NullString
	Description sql.NullString
	ReleaseDate sql.NullString
}

func (q *Queries) ListCatalogEntries(ctx context.Context, userID int64) ([]ListCatalogEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCatalogEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatalogEntriesRow
	for rows.Next() {
		var i ListCatalogEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.CoverUrl,
			&i.Description,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogEntriesByStatus = `-- name: ListCatalogEntriesByStatus :many
SELECT ce.id, ce.user_id, ce.game_id, ce.status, ce.created_at, ce.updated_at,
       g.title, g.cover_url, g.description, g.release_date
FROM catalog_entries ce
JOIN games g ON ce.game_id = g.id
WHERE ce.user_id = ? AND ce.status = ?
ORDER BY ce.updated_at DESC
`

type ListCatalogEntriesByStatusParams struct {
	UserID int64
	Status string
}

type ListCatalogEntriesByStatusRow struct {
	ID          int64
	UserID      int64
	GameID      int64
	Status      string
	CreatedAt   string
	UpdatedAt   string
	Title       string
	CoverUrl    sql.NullString
	Description sql.NullString
	ReleaseDate sql.NullString
}

func (q *Queries) ListCatalogEntriesByStatus(ctx context.Context, arg ListCatalogEntriesByStatusParams) ([]ListCatalogEntriesByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listCatalogEntriesByStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatalogEntriesByStatusRow
	for rows.Next() {
		var i ListCatalogEntriesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.CoverUrl,
			&i.Description,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCatalogEntryStatus = `-- name: UpdateCatalogEntryStatus :exec
UPDATE catalog_entries
SET status = ?, updated_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type UpdateCatalogEntryStatusParams struct {
	Status string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateCatalogEntryStatus(ctx context.Context, arg UpdateCatalogEntryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCatalogEntryStatus, arg.Status, arg.ID, arg.UserID)
	return err
}
