// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"
	"database/sql"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (rawg_id, title, cover_url, description, release_date)
VALUES (?, ?, ?, ?, ?)
RETURNING id, rawg_id, title, cover_url, description, release_date, created_at
`

type CreateGameParams struct {
	RawgID      sql.NullInt64
	Title       string
	CoverUrl    sql.NullString
	Description sql.NullString
	ReleaseDate sql.NullString
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.RawgID,
		arg.Title,
		arg.CoverUrl,
		arg.Description,
		arg.ReleaseDate,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.RawgID,
		&i.Title,
		&i.CoverUrl,
		&i.Description,
		&i.ReleaseDate,
		&i.CreatedAt,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, rawg_id, title, cover_url, description, release_date, created_at
FROM games
WHERE id = ?
`

func (q *Queries) GetGameByID(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.RawgID,
		&i.Title,
		&i.CoverUrl,
		&i.Description,
		&i.ReleaseDate,
		&i.CreatedAt,
	)
	return i, err
}

const getGameByRawgID = `-- name: GetGameByRawgID :one
SELECT id, rawg_id, title, cover_url, description, release_date, created_at
FROM games
WHERE rawg_id = ?
`

func (q *Queries) GetGameByRawgID(ctx context.Context, rawgID sql.NullInt64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByRawgID, rawgID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.RawgID,
		&i.Title,
		&i.CoverUrl,
		&i.Description,
		&i.ReleaseDate,
		&i.CreatedAt,
	)
	return i, err
}

const searchGames = `-- name: SearchGames :many
SELECT id, rawg_id, title, cover_url, description, release_date, created_at
FROM games
WHERE title LIKE '%' || ? || '%'
ORDER BY title
`

func (q *Queries) SearchGames(ctx context.Context, dollar_1 sql.NullString) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, searchGames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.RawgID,
			&i.Title,
			&i.CoverUrl,
			&i.Description,
			&i.ReleaseDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
