// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"database/sql"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (token, created_by, expires_at)
VALUES (?, ?, ?)
RETURNING id, token, created_by, expires_at, used_by, used_at, created_at
`

type CreateInvitationParams struct {
	Token     string
	CreatedBy int64
	ExpiresAt string
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, createInvitation, arg.Token, arg.CreatedBy, arg.ExpiresAt)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, token, created_by, expires_at, used_by, used_at, created_at
FROM invitations
WHERE token = ?
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitationsByUser = `-- name: ListInvitationsByUser :many
SELECT id, token, created_by, expires_at, used_by, used_at, created_at
FROM invitations
WHERE created_by = ?
ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByUser(ctx context.Context, createdBy int64) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listInvitationsByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.UsedBy,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useInvitation = `-- name: UseInvitation :exec
UPDATE invitations
SET used_by = ?, used_at = datetime('now')
WHERE id = ? AND used_by IS NULL
`

type UseInvitationParams struct {
	UsedBy sql.NullInt64
	ID     int64
}

func (q *Queries) UseInvitation(ctx context.Context, arg UseInvitationParams) error {
	_, err := q.db.ExecContext(ctx, useInvitation, arg.UsedBy, arg.ID)
	return err
}
