// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type CatalogEntry struct {
	ID        int64
	UserID    int64
	GameID    int64
	Status    string
	CreatedAt string
	UpdatedAt string
}

type Game struct {
	ID          int64
	RawgID      sql.NullInt64
	Title       string
	CoverUrl    sql.NullString
	Description sql.NullString
	ReleaseDate sql.NullString
	CreatedAt   string
}

type Invitation struct {
	ID        int64
	Token     string
	CreatedBy int64
	ExpiresAt string
	UsedBy    sql.NullInt64
	UsedAt    sql.NullString
	CreatedAt string
}

type Session struct {
	ID        string
	UserID    int64
	CreatedAt string
	ExpiresAt string
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    string
}
